version: '2.3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/SMS_analysis_event_streaming_uat.py --master -H http://master:8089
  
  worker1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/SMS_analysis_event_streaming_uat.py --worker --master-host master

  worker2:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/SMS_analysis_event_streaming_uat.py --worker --master-host master

  worker3:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/SMS_analysis_event_streaming_uat.py --worker --master-host master

  worker4:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/SMS_analysis_event_streaming_uat.py --worker --master-host master 